### ISSUE TITLE
Implementar la lectura de datos con fixtures, y hacer tests reales

### ISSUE THREAD

**Issue by leliel12** [juancgvazquez/skmrifilter#10]
- [x] mover los test de data dentro de `tests/test_data/`
- [x] Implementar fixtures dentro del archivo `tests/conftest.py` (buscar la documentacion para analisar su funcionamiento)
- [x] Los test_data de archivo (dado que tienen scikit-learn como dependencia) es recomendable usar joblib para serializar y decializar.
-  [x] los fixtures deberian tener un scope de sesion

El test deberia tener una forma como
```python
conftest.py
@pytest.fixture(scope="session") # LEEER BIEN ESO DEL SCOPE
def noisy():
    return joblib.load(TEST_DATA_PATH / "noisy_image.pkl')
```

```python
# test
def test_simple_transformer(noisy, noisy_wavelet):
    t_wavelet = ImageFilterTransformer(denoise_wavelet)
    transformed_image = t_wavelet.transform(noisy)
    npt.assert_array_almost_equal(transformed_image, test_wavelet, decimal=15)
```

**Comment by juancgvazquez** [comment]
Solved!
