### ISSUE TITLE
Tox style improvement

### ISSUE THREAD

**Issue by leliel12** [juancgvazquez/skmrifilter#11]
Cambiar el environment `style` por

Agregar `{posagrs}` en el testenv por default... averiguar su funcionalidad

```ini
skip_install = True
usedevelop = False
deps = flake8 
       flake8-import-order
       flake8-black
commands =
    flake8 setup.py skmrifilter/ tests/ {posargs}
```

**Comment by juancgvazquez** [comment]
Cambiar el environment style por ¿nada? para que sea el por defecto, o hay algún defecto en el texto del issue?

**Comment by leliel12** [comment]
Se me dieron vuelta el segundo parrafo y el snippet.

Ese posargs sirve para pasarle parametros desde tox al comando subyacente

podes hacer `tox -e style -- --coint` . Asi el *count* va a parar al comando que sea que ejecuta ese environment

**Comment by juancgvazquez** [comment]
si, lo del pos args lo leí, pero me habia quedado la duda de lo del style de arriba.... gracias!

**Comment by juancgvazquez** [comment]
t
